name: Build seeded images

on:
  schedule:
    - cron: '0 2 * * *'
  workflow_dispatch:

jobs:
  haiti:
    if: github.repository_owner == 'PIH'
    concurrency:
      group: build-seeded-images-haiti-${{ github.ref }}
      cancel-in-progress: true
    uses: PIH/openmrs-contrib-distro-tools/.github/workflows/build-seeded-image.yml@main
    with:
      image_name: partnersinhealth/zl-emr
      pih_config: haiti
    secrets: inherit

  mirebalais:
    if: github.repository_owner == 'PIH'
    concurrency:
      group: build-seeded-images-mirebalais-${{ github.ref }}
      cancel-in-progress: true
    uses: PIH/openmrs-contrib-distro-tools/.github/workflows/build-seeded-image.yml@main
    with:
      image_name: partnersinhealth/zl-emr
      pih_config: mirebalais
    secrets: inherit
