name: Build seeded images

on:
  schedule:
    - cron: '0 2 * * *'
  workflow_dispatch:

jobs:
  hum-ci:
    if: github.repository_owner == 'PIH'
    concurrency:
      group: build-seeded-images-hum-ci-${{ github.ref }}
      cancel-in-progress: true
    uses: PIH/openmrs-contrib-distro-tools/.github/workflows/build-seeded-image.yml@main
    with:
      image_name: partnersinhealth/zl-emr
      site: hum-ci
      pih_config: mirebalais,mirebalais-humci
    secrets: inherit

  ci:
    if: github.repository_owner == 'PIH'
    concurrency:
      group: build-seeded-images-ci-${{ github.ref }}
      cancel-in-progress: true
    uses: PIH/openmrs-contrib-distro-tools/.github/workflows/build-seeded-image.yml@main
    with:
      image_name: partnersinhealth/zl-emr
      site: ci
      pih_config: haiti,haiti-hsn,haiti-local-idgen
    secrets: inherit

  haitihivtest:
    if: github.repository_owner == 'PIH'
    concurrency:
      group: build-seeded-images-haitihivtest-${{ github.ref }}
      cancel-in-progress: true
    uses: PIH/openmrs-contrib-distro-tools/.github/workflows/build-seeded-image.yml@main
    with:
      image_name: partnersinhealth/zl-emr
      site: haitihivtest
      pih_config: haiti,haiti-hiv,haiti-hiv-ci
    secrets: inherit

  zl-ci:
    if: github.repository_owner == 'PIH'
    concurrency:
      group: build-seeded-images-zl-ci-${{ github.ref }}
      cancel-in-progress: true
    uses: PIH/openmrs-contrib-distro-tools/.github/workflows/build-seeded-image.yml@main
    with:
      image_name: partnersinhealth/zl-emr
      site: zl-ci
      pih_config: haiti,haiti-central,haiti-local-idgen
    secrets: inherit
