name: Build and deploy

on:
  push:
    branches: [master]
  workflow_dispatch:
  repository_dispatch:

jobs:
  build-and-publish:
    if: github.repository_owner == 'PIH'
    concurrency:
      group: build-and-deploy-${{ github.ref }}
      cancel-in-progress: true
    uses: PIH/openmrs-contrib-distro-tools/.github/workflows/build-and-deploy-to-openmrs-jfrog.yml@main
    with:
      image_name: partnersinhealth/zl-emr
      maven_profiles: distro-zip
      notify_ci_dashboard: true
    secrets: inherit

  smoke-tests:
    if: github.repository_owner == 'PIH'
    needs: build-and-publish
    concurrency:
      group: smoke-tests-${{ github.ref }}
      cancel-in-progress: true
    uses: ./.github/workflows/smoke-tests.yml
    secrets: inherit

  deploy-to-hum-ci:
    if: github.repository_owner == 'PIH'
    needs: build-and-publish
    concurrency:
      group: deploy-to-hum-ci-${{ github.ref }}
      cancel-in-progress: true
    uses: PIH/openmrs-contrib-distro-tools/.github/workflows/deploy-via-runner.yml@main
    with:
      runner-label: humci
      notify_ci_dashboard: true
    secrets: inherit

  deploy-to-ci:
    if: github.repository_owner == 'PIH'
    needs: build-and-publish
    concurrency:
      group: deploy-to-ci-${{ github.ref }}
      cancel-in-progress: true
    uses: PIH/openmrs-contrib-distro-tools/.github/workflows/deploy-via-runner.yml@main
    with:
      runner-label: ci
      notify_ci_dashboard: true
    secrets: inherit

  deploy-to-haitihivtest:
    if: github.repository_owner == 'PIH'
    needs: build-and-publish
    concurrency:
      group: deploy-to-haitihivtest-${{ github.ref }}
      cancel-in-progress: true
    uses: PIH/openmrs-contrib-distro-tools/.github/workflows/deploy-via-runner.yml@main
    with:
      runner-label: haitihivtest
      notify_ci_dashboard: true
    secrets: inherit

  deploy-to-zl-ci:
    if: github.repository_owner == 'PIH'
    needs: build-and-publish
    concurrency:
      group: deploy-to-zl-ci-${{ github.ref }}
      cancel-in-progress: true
    uses: PIH/openmrs-contrib-distro-tools/.github/workflows/deploy-via-runner.yml@main
    with:
      runner-label: zl-ci
      notify_ci_dashboard: true
    secrets: inherit
