name: Release new version

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  release:
    uses: PIH/openmrs-contrib-distro-tools/.github/workflows/release-to-openmrs-jfrog.yml@main
    with:
      image_name: partnersinhealth/zl-emr
      image_variants: |
        java8=amazoncorretto-8
      maven_profiles: distro-zip
    secrets: inherit
