name: Smoke tests

on:
  workflow_dispatch:

jobs:
  haiti:
    if: github.repository_owner == 'PIH'
    uses: PIH/openmrs-contrib-distro-tools/.github/workflows/smoke-test.yml@main
    with:
      image_name: partnersinhealth/zl-emr
      pih_config: haiti
      suite: zlCentral
    secrets: inherit
