name=${project.name}
version=${project.version}

parent.groupId=${parentGroup}
parent.artifactId=${parentArtifact}
parent.version=${parentVersion}
parent.type=${parentType}

content.${parentContentArtifactId}=${parentContentVersion}
content.${parentContentArtifactId}.groupId=${parentContentGroupId}
content.${parentContentArtifactId}.namespace=

content.${contentArtifact}=${contentVersion}
content.${contentArtifact}.groupId=${contentGroup}
content.${contentArtifact}.namespace=

spa.artifactId=${frontendArtifact}
spa.groupId=${frontendGroup}
spa.version=${frontendVersion}
spa.type=${frontendType}
spa.includes=${frontendArtifact}-${frontendVersion}

property.pih.config.prompt=Specify PIH config (mirebalais,mirebalais-humci | haiti,haiti-hsn,haiti-local-idgen | haiti,haiti-hiv,haiti-hiv-ci | haiti,haiti-central,haiti-local-idgen)?
property.pih.config.default=haiti,haiti-central,haiti-local-idgen

var.encounterType.PATIENT_REGISTRATION.name=Enregistrement de patient
var.encounterType.CHECK_IN.name=Inscription
var.encounterType.MEDICATION_DISPENSED.name=M\u00e9dicaments administr\u00e9s
var.encounterType.VITALS.name=Signes vitaux
